import { Stagiaire } from "@/types"

export const demoStagiaires: Stagiaire[] = [
  {
    id: "1",
    candidat: "Adnan Tomi",
    filiere: "Génie Électrique",
    etablissement: "ENSA Oujda",
    numeroTelephone: "+212 6 00 00 00 01",
    email: "Salmi0009@gmail.com",
    dateDebut: "2026-02-02",
    dateFin: "2026-06-12",
    typeStage: "PFA",
  },
  {
    id: "2",
    candidat: "Dahbi Abderrahim",
    filiere: "Génie Électrique",
    etablissement: "ENSA Tanger",
    numeroTelephone: "+212 6 00 00 00 02",
    email: "ahmedbaj@gmail.com",
    dateDebut: "2026-01-15",
    dateFin: "2026-04-17",
    typeStage: "PFE",
  },
  {
    id: "3",
    candidat: "Mouad Dami",
    filiere: "Génie Électrique",
    etablissement: "ENSA Tanger",
    numeroTelephone: "+212 6 00 00 00 03",
    email: "bono@gmail.com",
    dateDebut: "2026-01-09",
    dateFin: "2026-05-12",
    typeStage: "PFE",
  },
  {
    id: "4",
    candidat: "Saad Douar",
    filiere: "Informatique",
    etablissement: "ENSA Safi",
    numeroTelephone: "+212 6 00 00 00 04",
    email: "saaddouarr@gmail.com",
    dateDebut: "2026-02-03",
    dateFin: "2026-06-06",
    typeStage: "PFE",
  },
  {
    id: "5",
    candidat: "Ikram Douar",
    filiere: "Informatique et Réseau",
    etablissement: "EMSI",
    numeroTelephone: "+212 6 00 00 00 05",
    email: "saaddouarr@gmail.com",
    dateDebut: "2026-02-09",
    dateFin: "2026-04-30",
    typeStage: "PFE",
  },
  {
    id: "6",
    candidat: "Taha El-Ghzizel",
    filiere: "Chimie des matériaux et génie des procédés",
    etablissement: "École nationale supérieure de chimie de Kénitra",
    numeroTelephone: "+212 6 00 00 00 06",
    email: "taha.el-ghzizel@uit.ac.ma",
    dateDebut: "2026-01-11",
    dateFin: "2026-06-18",
    typeStage: "PFE",
  },
  {
    id: "7",
    candidat: "Taha El-Ghzizel",
    filiere: "Chimie des matériaux et génie des procédés",
    etablissement: "École nationale supérieure de chimie de Kénitra",
    numeroTelephone: "+212 6 00 00 00 06",
    email: "taha.el-ghzizel@uit.ac.ma",
    dateDebut: "2026-06-01",
    dateFin: "2026-09-02",
    typeStage: "PFA",
  },
  {
    id: "8",
    candidat: "Basma Oubrahim",
    filiere: "Génie Électrique",
    etablissement: "Faculté des sciences ain chock Casablanca",
    numeroTelephone: "+212 6 00 00 00 07",
    email: "oubrahim.basma@gmail.com",
    dateDebut: "2026-05-20",
    dateFin: "2026-08-25",
    typeStage: "PFA",
  },
  {
    id: "9",
    candidat: "Yasmine El Amrani",
    filiere: "Génie Informatique",
    etablissement: "Faculté des Sciences et Techniques de Settat",
    numeroTelephone: "+212 6 00 00 00 08",
    email: "yasmine.elamrani@fst-settat.ac.ma",
    dateDebut: "2026-06-15",
    dateFin: "2026-09-15",
    typeStage: "PFA",
  },
  {
    id: "10",
    candidat: "Omar Benali",
    filiere: "Génie Mécanique",
    etablissement: "ENSAM Casablanca",
    numeroTelephone: "+212 6 00 00 00 09",
    email: "omar.benali@ensam.ma",
    dateDebut: "2026-07-01",
    dateFin: "2026-10-01",
    typeStage: "Stage d'application",
  },
]

export const filieres = [
  "Génie Électrique",
  "Informatique",
  "Informatique et Réseau",
  "Chimie des matériaux et génie des procédés",
  "Génie Informatique",
  "Génie Mécanique",
]

export const etablissements = [
  "ENSA Oujda",
  "ENSA Tanger",
  "ENSA Safi",
  "EMSI",
  "École nationale supérieure de chimie de Kénitra",
  "Faculté des sciences ain chock Casablanca",
  "Faculté des Sciences et Techniques de Settat",
  "ENSAM Casablanca",
]
